// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_sy6Xjrshbm5uYhX2gmKSFzRykdg3RTg',
    appId: '1:744379016213:web:47db6ca220a97d10899a1c',
    messagingSenderId: '744379016213',
    projectId: 'kitchen-assistant-d507d',
    authDomain: 'kitchen-assistant-d507d.firebaseapp.com',
    storageBucket: 'kitchen-assistant-d507d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhvm5MfWf-w1xfzG_CWX_cwQwp8M5-L7c',
    appId: '1:744379016213:android:eb1ba687c7b4c9d4899a1c',
    messagingSenderId: '744379016213',
    projectId: 'kitchen-assistant-d507d',
    storageBucket: 'kitchen-assistant-d507d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTGdsGRwfU2ENA2XQDQ2ygIJWdfftSkLk',
    appId: '1:744379016213:ios:89cd4b66ca48e57c899a1c',
    messagingSenderId: '744379016213',
    projectId: 'kitchen-assistant-d507d',
    storageBucket: 'kitchen-assistant-d507d.firebasestorage.app',
    iosBundleId: 'com.example.kitchenAssistant',
  );
}
